const theme = {
  colors: {
    textPrimary: "#2c2841",
    primary: "#ffff",
    greenText: "#2da10a",
    black: "#121010",
    blue: "#3498db",
    blueDark: "#2c3e50",
    blueLiht: "#d6eaf9",
    red: "#f33322",
    redLinht: "#fe857f",
    redBlack: "#bd3124",
    greenLiht: "#c5e5bc",
    greenOpacity: "#e7eddf",
    greenMedium: "#98d187",
    green: "#42aa21",
    greenWhatsapp: "#25D366",
    yellow: "#f9ba00",
    yellowLight: "#fcd34df9",
    grey: "#f4f5ed",
    greyMedium: "#ccc",
    greyBlack: "#888",
    greyDark: "#333333",
    opacity: "#ffffffa0",
    white: "#fff",
    whiteMedium: "#f5f5f5",
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    backgroundColorWhite: "#ffffffa0",
    backgroundColorBlack: "rgba(0, 0, 0, 0.5)",
  },
  fontSizes: {
    body: 18,
    titles: 22,
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 999,
  },
};

export default theme;
