const string = {
  welcome: {
    hello: "¿Hola buen día como estas?",
    welcomeHappy: "El campo te da la bienvenida desde tu celular",
    chat: "Puedes escribirnos y conversaremos un rato",
    registerNewUserA: "Regístrate hoy y recibe",
    registerNewUserB: "Descuentos en tus primeras órdenes",
    message: "Aplican para usuarios nuevos",
    tyc: "Aplican T&C",
    registrate: "Regístrate",
  },
  Signup: {
    hello: "Bienvenidos al campo",
    name: "Nombre y apellido",
    mail: "Email (correo electrónico)",
    cell: "Numero de celular",
    password: "Contraseña",
    city: "Municipio",
    require: "Rellena los espacios para registrarte correctamente",
    message: "Aplican para usuarios nuevos",
    tyc: "Aplican T&C",
    registrate: "Regístrate",
    registerNewUserA: "Ya tengo cuenta ",
    errors: {
      name: "*Ingresa tu nombre completo",
      city: "*Ingresa tu municipio",
      password: "*Ingresa una mejor contraseña",
      cell: "*Numero de telefono requerido",
      mail: "*Ingresa tu correo para identificar la cuenta",
    },
  },
  login: {
    next: "Ingresar",
    require: "Confirmemos tu identidad",
    hello: "Bienvenido nuevamente al campo",
  },
  client: {
    search: "Buscar en el campo",
    near: "Fincas mas cerca de ti",
    select: "Selecciona tu vereda favorita",
    searchDistric: "Busca tu vereda",
    require: "Rellena los espacios para registrarte correctamente",
    message: "Aplican para usuarios nuevos",
    tyc: "Aplican T&C",
    registrate: "Regístrate",
    registerNewUserA: "Ya tengo cuenta ",
    favorite: "Favorito",
    cart: "Ver Carrito",
    Shopping: "Seguir Comprando",
    add: "Agregar al carrito",
    addCart: "Complementa tu carrito",
    summaey: "Resumen",
    AddCode: "Agrega código \n promocional",
    codes: "Códigos promocionales",
    apply: "Aplicar",
    subtotal: "Subtotal",
    delivery: "Domicilio",
    total: "Total",
    cash: "Pago en efectivo",
    messagePay:
      "Recuerda realizar el pago en efectivo al domiciliario con billetes de baja categoría",
    pay: "Realizar pago",
    noCartMessage: "No tienes ningún articulo en tu carro",
    new: "Inicia un carrito nuevo",
    home: "Inicio",
    chat: "Chat",
    profile: "Cuenta",
    favoriteStore: "Aqui estan tus tiendas favoritas",
  },
  homeSeller: {
    ADD_PRODUCT: "Agregar Producto",
    PRODUCT_ADDED: "Producto agregado!",
    PRODUCT_NAME: "Nombre del Producto",
    CATEGORY: "Categoría",
    DESCRIPTION: "Descripción del Producto",
    PRICE: "Precio",
    STOCK: "Stock",
    CAMERA_PERMISSION: "Se necesita acceso a la cámara.",
    GALLERY_PERMISSION: "Se necesita acceso a la galería.",
  },
  alertAddProduct: {
    CAMERA_PERMISSION: "Se necesita acceso a la cámara.",
    GALLERY_PERMISSION: "Se necesita acceso a la galería.",
    PRODUCT_ADDED: "Producto agregado!",
  },
  App: {
    next: "Continuar",
    redy: "Iniciar",
    home: "Inicio",
    chat: "chat",
    account: "Cuenta",
    require: "*OBLIGATORIO*",
  },
  FloatingActionButtons: {
    openGoogleMaps: "Abrir en Google Maps",
    changeMap: "Cambiar Mapa",
  },
  LoadingIndicator: {
    loading: "Cargando...",
    loadingRoute: "Cargando Ruta...",
    locationPermission: "Acepta los permisos para poder tu localización",
  },
  MapBtn: {
    arriveAtStore: "Llegué a la tienda",
    arriveAtClient: "Llegué al Destino",
  },
  ProductList: {
    quantityLabel: "Cantidad:",
    unitLabel: "Unidad",
    priceLabel: "Precio:",
  },
  PaymentSwitch: {
    paidStatus: "Estado de Pago",
  },
  StopInfo: {
    stopTitle: "Parada {index}:",
    store: "Tienda: ",
    pays: "Pagas: ",
    productsCount: "productos",
  },
  Button: {
    reservation: "Reservar",
    confirm: "Confirmar",
    cancel: "Cancelar",
  },
  Order: {
    orderId: "Pedido ID: ",
    orders: "Órdenes: ",
    stops: "Paradas: ",
    distance: "Distancia: ",
    totalPay: "Total a pagar: ",
    totalProducts: "Total de productos: ",
    viewOrder: "Ver Pedido",
    acceptOrder: "Aceptar pedido",
    cancelOrder: "Cancelar Pedido",
    confirmationCancel: "¿Está seguro de que desea cancelar este pedido?",
    cancelMessage: "Pedido cancelado",
  },
  OrderDetails: {
    orderId: "Pedido No:",
    title: "Detalle del pedido",
    continueDelivery: "Continuar Entregando",
    productCount: "Productos:",
    routeButton: "Ver Ruta",
    takeOrderButton: "Tomar Pedido",
    takenButton: "Tomado",
  },
  OrderTotals: {
    totalProducts: "Total de Productos: ",
    totalCost: "Costo Total: $",
    totalToPay: "Total a Pagar (incluye envío): $",
  },
  TimeAlertStatus: {
    started: "Pedido en progreso",
    notStarted: "Pedido pendiente",
  },
  TimeAlert: {
    timeLeft: "Tiempo restante: ",
    status: "Estado: ",
  },
  CompletedDeliveriesMessage: {
    title: "Entregas Completadas",
    subtitle: "¡Gracias por su esfuerzo!",
  },
};

export default string;
